name: archery_tracker
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.2

  # State Management
  flutter_riverpod: ^2.4.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Serialization
  json_annotation: ^4.9.0

  # UUID Generation
  uuid: ^4.2.1

  # Date Handling
  intl: ^0.19.0

  # Preferences Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
